# Generated by Django 5.0.2 on 2024-02-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images', upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
